export type TriviaCard = {
  id: string;
  teaser: string;
  reveal: string;
  category: string;
  difficulty: "easy" | "medium" | "hard";
  rotationWeight: number;
};

export const TRIVIA: TriviaCard[] = [
  { id: "t001", teaser: "Which nation has won the most World Cups?", reveal: "Brazil, with 5 titles (1958, 1962, 1970, 1994, 2002).", category: "records", difficulty: "easy", rotationWeight: 5 },
  { id: "t002", teaser: "Who is the all-time top scorer in World Cup history?", reveal: "Miroslav Klose of Germany, with 16 goals.", category: "records", difficulty: "medium", rotationWeight: 5 },
  { id: "t003", teaser: "Which player has appeared in the most World Cup matches?", reveal: "Lionel Messi, who passed Lothar Matthäus to reach 26 games.", category: "records", difficulty: "medium", rotationWeight: 5 },
  { id: "t004", teaser: "Who hosted and won the very first World Cup in 1930?", reveal: "Uruguay, who beat Argentina 4–2 in the final.", category: "history", difficulty: "medium", rotationWeight: 5 },
  { id: "t005", teaser: "Which three countries are hosting the 2026 World Cup?", reveal: "The United States, Canada and Mexico.", category: "2026", difficulty: "easy", rotationWeight: 5 },
  { id: "t006", teaser: "How many teams play in the 2026 World Cup?", reveal: "48 teams — the largest field in World Cup history.", category: "2026", difficulty: "easy", rotationWeight: 5 },
  { id: "t007", teaser: "Who scored the most goals in a single World Cup?", reveal: "Just Fontaine of France, with 13 goals at the 1958 tournament.", category: "records", difficulty: "hard", rotationWeight: 5 },
  { id: "t008", teaser: "Which country has reached the most World Cup finals?", reveal: "Germany, with 8 final appearances.", category: "records", difficulty: "hard", rotationWeight: 5 },
  { id: "t009", teaser: "How old was Pelé when he scored in the 1958 final?", reveal: "17 — he remains the youngest player to score in a World Cup final.", category: "players", difficulty: "medium", rotationWeight: 5 },
  { id: "t010", teaser: "How many matches will the 2026 World Cup feature?", reveal: "104 matches, up from 64 in the 32-team format.", category: "2026", difficulty: "medium", rotationWeight: 5 },
  { id: "t011", teaser: "What new knockout round debuts at the 2026 World Cup?", reveal: "The Round of 32, created by the expanded 48-team field.", category: "2026", difficulty: "easy", rotationWeight: 5 },
  { id: "t012", teaser: "How many groups are there at the 2026 World Cup?", reveal: "12 groups of four teams, labelled A to L.", category: "2026", difficulty: "easy", rotationWeight: 5 },
  { id: "t013", teaser: "Where is the 2026 World Cup final being played?", reveal: "MetLife Stadium in East Rutherford, New Jersey.", category: "2026", difficulty: "medium", rotationWeight: 5 },
  { id: "t014", teaser: "Which stadium hosts the 2026 World Cup opening match?", reveal: "Estadio Azteca in Mexico City.", category: "2026", difficulty: "medium", rotationWeight: 5 },
  { id: "t015", teaser: "Who is the only player to win the World Cup three times?", reveal: "Pelé of Brazil — champion in 1958, 1962 and 1970.", category: "players", difficulty: "medium", rotationWeight: 5 },
  { id: "t016", teaser: "Which country won the first World Cup held in Asia?", reveal: "Brazil, at the 2002 tournament co-hosted by South Korea and Japan.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t017", teaser: "Who won the 2022 World Cup in Qatar?", reveal: "Argentina, beating France on penalties after a 3–3 draw.", category: "history", difficulty: "easy", rotationWeight: 1 },
  { id: "t018", teaser: "Which European nation has won the most World Cups?", reveal: "Germany and Italy are tied on 4 titles each.", category: "records", difficulty: "medium", rotationWeight: 1 },
  { id: "t019", teaser: "Who scored a hat-trick in a World Cup final?", reveal: "Geoff Hurst of England, in the 1966 final against West Germany.", category: "history", difficulty: "hard", rotationWeight: 1 },
  { id: "t020", teaser: "Which African nation first reached a World Cup quarter-final?", reveal: "Cameroon, at Italy 1990.", category: "history", difficulty: "hard", rotationWeight: 1 },
  { id: "t021", teaser: "Who is the youngest player ever to play at a World Cup?", reveal: "Norman Whiteside of Northern Ireland, aged 17 in 1982.", category: "players", difficulty: "hard", rotationWeight: 1 },
  { id: "t022", teaser: "Which goalkeeper is famous for the 'Hand of God' concession?", reveal: "Peter Shilton of England, beaten by Maradona in 1986.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t023", teaser: "Who scored the 'Goal of the Century' in 1986?", reveal: "Diego Maradona, dribbling past England from his own half.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t024", teaser: "Which country hosted the 1994 World Cup?", reveal: "The United States.", category: "hosts", difficulty: "easy", rotationWeight: 1 },
  { id: "t025", teaser: "Which two countries co-hosted the 2002 World Cup?", reveal: "South Korea and Japan.", category: "hosts", difficulty: "medium", rotationWeight: 1 },
  { id: "t026", teaser: "Who won the Golden Boot at the 2022 World Cup?", reveal: "Kylian Mbappé of France, with 8 goals.", category: "players", difficulty: "medium", rotationWeight: 1 },
  { id: "t027", teaser: "Which nation lost three World Cup finals in the 1990s and beyond before winning?", reveal: "Argentina endured final heartbreak before winning again in 2022.", category: "history", difficulty: "hard", rotationWeight: 1 },
  { id: "t028", teaser: "What is the current World Cup trophy called?", reveal: "The FIFA World Cup Trophy, used since 1974.", category: "trophy", difficulty: "medium", rotationWeight: 1 },
  { id: "t029", teaser: "What was the original World Cup trophy named?", reveal: "The Jules Rimet Trophy, awarded from 1930 to 1970.", category: "trophy", difficulty: "hard", rotationWeight: 1 },
  { id: "t030", teaser: "Which country kept the Jules Rimet Trophy permanently?", reveal: "Brazil, after winning their third title in 1970.", category: "trophy", difficulty: "hard", rotationWeight: 1 },
  { id: "t031", teaser: "Who scored the fastest goal in World Cup history?", reveal: "Hakan Şükür of Turkey, after about 11 seconds in 2002.", category: "records", difficulty: "hard", rotationWeight: 1 },
  { id: "t032", teaser: "Which host nation has never gotten past the group stage as hosts?", reveal: "South Africa, who exited in the group stage as 2010 hosts.", category: "hosts", difficulty: "hard", rotationWeight: 1 },
  { id: "t033", teaser: "Who is the only goalkeeper to win the Golden Ball?", reveal: "Oliver Kahn of Germany, at the 2002 World Cup.", category: "goalkeepers", difficulty: "hard", rotationWeight: 1 },
  { id: "t034", teaser: "Which country won the inaugural World Cup on home soil in 1930?", reveal: "Uruguay.", category: "history", difficulty: "easy", rotationWeight: 1 },
  { id: "t035", teaser: "How many World Cups has Italy won?", reveal: "Four — in 1934, 1938, 1982 and 2006.", category: "records", difficulty: "medium", rotationWeight: 1 },
  { id: "t036", teaser: "Who captained France to the 1998 World Cup title?", reveal: "Didier Deschamps, who later won it again as manager.", category: "players", difficulty: "medium", rotationWeight: 1 },
  { id: "t037", teaser: "Who has won the World Cup as both player and manager?", reveal: "Three men: Mário Zagallo, Franz Beckenbauer and Didier Deschamps.", category: "managers", difficulty: "hard", rotationWeight: 1 },
  { id: "t038", teaser: "Which country has played in every World Cup?", reveal: "Brazil — the only team to appear at every edition.", category: "records", difficulty: "medium", rotationWeight: 1 },
  { id: "t039", teaser: "Who scored in the 2018 World Cup final for France?", reveal: "Antoine Griezmann, Paul Pogba and Kylian Mbappé.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t040", teaser: "Which nation did Croatia beat to reach the 2018 final?", reveal: "England, in the semi-final.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t041", teaser: "Which Asian team reached the semi-finals in 2002?", reveal: "South Korea, as co-hosts.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t042", teaser: "Who won the Golden Ball at the 2022 World Cup?", reveal: "Lionel Messi of Argentina.", category: "players", difficulty: "easy", rotationWeight: 1 },
  { id: "t043", teaser: "How many goals did Diego Maradona score at the 1986 World Cup?", reveal: "Five, as he dragged Argentina to the title.", category: "players", difficulty: "hard", rotationWeight: 1 },
  { id: "t044", teaser: "Which country reached the final on home soil in 1950 but lost?", reveal: "Brazil, beaten by Uruguay in the 'Maracanazo'.", category: "history", difficulty: "hard", rotationWeight: 1 },
  { id: "t045", teaser: "Who is England's record World Cup goalscorer?", reveal: "Gary Lineker, with 10 World Cup goals.", category: "players", difficulty: "hard", rotationWeight: 1 },
  { id: "t046", teaser: "Which nation won its first World Cup in 2010?", reveal: "Spain, beating the Netherlands in the final.", category: "history", difficulty: "easy", rotationWeight: 1 },
  { id: "t047", teaser: "Where was the 2010 World Cup held?", reveal: "South Africa — the first on the African continent.", category: "hosts", difficulty: "easy", rotationWeight: 1 },
  { id: "t048", teaser: "Who scored the winning goal in the 2010 final?", reveal: "Andrés Iniesta of Spain, in extra time.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t049", teaser: "Which country won the 2014 World Cup?", reveal: "Germany, beating Argentina 1–0 after extra time.", category: "history", difficulty: "easy", rotationWeight: 1 },
  { id: "t050", teaser: "What was the score when Germany beat the host in the 2014 semi-final?", reveal: "Germany 7–1 Brazil.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t051", teaser: "Who scored the 2014 World Cup-winning goal?", reveal: "Mario Götze of Germany.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t052", teaser: "Which country hosted the 2014 World Cup?", reveal: "Brazil.", category: "hosts", difficulty: "easy", rotationWeight: 1 },
  { id: "t053", teaser: "Who is Germany's record World Cup goalscorer?", reveal: "Miroslav Klose, with 16 goals across four tournaments.", category: "players", difficulty: "medium", rotationWeight: 1 },
  { id: "t054", teaser: "Which player held the World Cup appearance record before Messi?", reveal: "Lothar Matthäus held it with 25 games.", category: "records", difficulty: "hard", rotationWeight: 1 },
  { id: "t055", teaser: "Which country reached its first World Cup final in 2018?", reveal: "Croatia, losing 4–2 to France.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t056", teaser: "Who won the Golden Ball at the 2018 World Cup?", reveal: "Luka Modrić of Croatia.", category: "players", difficulty: "medium", rotationWeight: 1 },
  { id: "t057", teaser: "How many World Cups has Argentina won?", reveal: "Three — in 1978, 1986 and 2022.", category: "records", difficulty: "medium", rotationWeight: 1 },
  { id: "t058", teaser: "How many World Cups has France won?", reveal: "Two — in 1998 and 2018.", category: "records", difficulty: "easy", rotationWeight: 1 },
  { id: "t059", teaser: "How many World Cups has Uruguay won?", reveal: "Two — in 1930 and 1950.", category: "records", difficulty: "medium", rotationWeight: 1 },
  { id: "t060", teaser: "Which player scored in two different World Cup finals for France?", reveal: "Kylian Mbappé, scoring in 2018 and a hat-trick in 2022.", category: "players", difficulty: "hard", rotationWeight: 1 },
  { id: "t061", teaser: "Who scored a hat-trick in a losing World Cup final?", reveal: "Kylian Mbappé, in the 2022 final.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t062", teaser: "Which African nation reached the semi-finals in 2022?", reveal: "Morocco — the first African team to do so.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t063", teaser: "Which nation knocked out Spain and Portugal on the way to the 2022 semis?", reveal: "Morocco.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t064", teaser: "Who was the 2022 World Cup's best young player?", reveal: "Enzo Fernández of Argentina.", category: "players", difficulty: "hard", rotationWeight: 1 },
  { id: "t065", teaser: "Which goalkeeper won the Golden Glove in 2022?", reveal: "Emiliano Martínez of Argentina.", category: "goalkeepers", difficulty: "medium", rotationWeight: 1 },
  { id: "t066", teaser: "What colour cards were first used at a World Cup in 1970?", reveal: "Yellow and red cards were introduced at Mexico 1970.", category: "history", difficulty: "hard", rotationWeight: 1 },
  { id: "t067", teaser: "When was the first World Cup held?", reveal: "1930, in Uruguay.", category: "history", difficulty: "easy", rotationWeight: 1 },
  { id: "t068", teaser: "Which two World Cups were cancelled, and why?", reveal: "1942 and 1946, because of the Second World War.", category: "history", difficulty: "hard", rotationWeight: 1 },
  { id: "t069", teaser: "Who scored in five different World Cups for Portugal?", reveal: "Cristiano Ronaldo of Portugal.", category: "players", difficulty: "hard", rotationWeight: 1 },
  { id: "t070", teaser: "Which player scored in five different World Cups?", reveal: "Cristiano Ronaldo of Portugal.", category: "players", difficulty: "hard", rotationWeight: 1 },
  { id: "t071", teaser: "Which host nation won the World Cup most recently?", reveal: "France, on home soil in 1998.", category: "hosts", difficulty: "medium", rotationWeight: 1 },
  { id: "t072", teaser: "How many host nations have won the World Cup?", reveal: "Six: Uruguay, Italy, England, West Germany, Argentina and France.", category: "hosts", difficulty: "hard", rotationWeight: 1 },
  { id: "t073", teaser: "Which country hosted the 1966 World Cup?", reveal: "England, who also won it.", category: "hosts", difficulty: "easy", rotationWeight: 1 },
  { id: "t074", teaser: "Who scored England's winning goals in the 1966 final?", reveal: "Geoff Hurst, with a hat-trick.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t075", teaser: "Which country has finished as runner-up the most times?", reveal: "Germany, with four runner-up finishes.", category: "records", difficulty: "hard", rotationWeight: 1 },
  { id: "t076", teaser: "How many World Cup finals has the Netherlands lost?", reveal: "Three — 1974, 1978 and 2010.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t077", teaser: "Who pioneered 'Total Football' at the 1974 World Cup?", reveal: "The Netherlands, led by Johan Cruyff.", category: "history", difficulty: "hard", rotationWeight: 1 },
  { id: "t078", teaser: "Which country won the 1970 World Cup, widely called the greatest team ever?", reveal: "Brazil.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t079", teaser: "What is awarded to the World Cup's best player?", reveal: "The Golden Ball.", category: "trophy", difficulty: "easy", rotationWeight: 1 },
  { id: "t080", teaser: "What is awarded to the World Cup's top scorer?", reveal: "The Golden Boot.", category: "trophy", difficulty: "easy", rotationWeight: 1 },
  { id: "t081", teaser: "What is awarded to the World Cup's best goalkeeper?", reveal: "The Golden Glove.", category: "trophy", difficulty: "medium", rotationWeight: 1 },
  { id: "t082", teaser: "How many teams played in the first 1930 World Cup?", reveal: "13 teams.", category: "history", difficulty: "hard", rotationWeight: 1 },
  { id: "t083", teaser: "When did the World Cup expand to 32 teams?", reveal: "At France 1998.", category: "format", difficulty: "medium", rotationWeight: 1 },
  { id: "t084", teaser: "When did the World Cup expand to 24 teams?", reveal: "At Spain 1982.", category: "format", difficulty: "hard", rotationWeight: 1 },
  { id: "t085", teaser: "Which country first won the World Cup outside its own continent?", reveal: "Brazil, winning in Sweden in 1958.", category: "history", difficulty: "hard", rotationWeight: 1 },
  { id: "t086", teaser: "Who scored the first goal in World Cup history?", reveal: "Lucien Laurent of France, in 1930.", category: "history", difficulty: "hard", rotationWeight: 1 },
  { id: "t087", teaser: "Which country eliminated Brazil in the 2022 quarter-finals?", reveal: "Croatia, on penalties.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t088", teaser: "How many World Cup titles do England have?", reveal: "One, in 1966.", category: "records", difficulty: "easy", rotationWeight: 1 },
  { id: "t089", teaser: "Which country won back-to-back World Cups in 1934 and 1938?", reveal: "Italy.", category: "history", difficulty: "hard", rotationWeight: 1 },
  { id: "t090", teaser: "Which country won back-to-back titles in 1958 and 1962?", reveal: "Brazil.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t091", teaser: "Who converted the winning penalty for Germany in the 1990 final?", reveal: "Andreas Brehme converted the winning penalty against Argentina.", category: "history", difficulty: "hard", rotationWeight: 1 },
  { id: "t092", teaser: "Which famous incident saw Zinedine Zidane sent off in a final?", reveal: "His headbutt on Marco Materazzi in the 2006 final.", category: "history", difficulty: "medium", rotationWeight: 1 },
  { id: "t093", teaser: "Which country won the 2006 World Cup?", reveal: "Italy, beating France on penalties.", category: "history", difficulty: "easy", rotationWeight: 1 },
  { id: "t094", teaser: "Where was the 2006 World Cup held?", reveal: "Germany.", category: "hosts", difficulty: "easy", rotationWeight: 1 },
  { id: "t095", teaser: "Which nation has appeared in the most World Cups without winning?", reveal: "Mexico, a regular qualifier still chasing a first title.", category: "records", difficulty: "hard", rotationWeight: 1 },
  { id: "t096", teaser: "Which country reached the 2018 final alongside France?", reveal: "Croatia.", category: "history", difficulty: "easy", rotationWeight: 1 },
  { id: "t097", teaser: "How many times has the World Cup been held in North America before 2026?", reveal: "Twice — Mexico 1970 and 1986, plus the USA 1994.", category: "hosts", difficulty: "hard", rotationWeight: 1 },
  { id: "t098", teaser: "Which country will play the 2026 opener at the Estadio Azteca?", reveal: "Mexico, the home nation in Group A.", category: "2026", difficulty: "medium", rotationWeight: 1 },
  { id: "t099", teaser: "On what date is the 2026 World Cup final?", reveal: "July 19, 2026.", category: "2026", difficulty: "medium", rotationWeight: 1 },
  { id: "t100", teaser: "How many of the 12 group third-placed teams reach the 2026 knockouts?", reveal: "The eight best third-placed teams advance.", category: "2026", difficulty: "medium", rotationWeight: 1 }
];
